site_name: github-docs
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
plugins:
  - mermaid2:
      version: 11.9.0
  - offline
  - privacy
  - search
markdown_extensions: 
  - admonition
  - attr_list
  - codehilite
  - pymdownx.blocks.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Introduction: index.md
